const discord = require('discord.js')
const db = require('quick.db')
const fs = require('fs')
exports.run = (client, message, args) => {
    if(message.channel.type === 'dm') return message.channel.send(`This is not a dm channel command.`)
    message.delete()
    let help = new discord.RichEmbed()
        .setTitle(`Help for announcement command!`)
        .setDescription(`Usage: !announce #[channel] [text]\nAdmin permission required!`)
        .setColor("BLUE")
        .setTimestamp()
        .setFooter(`hurt#6666 <3`)
    if(!message.member.hasPermission('ADMINISTRATOR')) return message.channel.send(`You do not have permission to make announcements!`)
    if(!args[0]) return message.channel.send(help)
    if(!args[1]) return message.channel.send(help)
    let mg = args.slice(1).join(" ")
    if(!mg){
        let help = new discord.RichEmbed()
        .setTitle(`Help for announcement command!`)
        .setDescription(`Usage: !announce #[channel] [text]\nAdmin permission required!`)
        .setColor("BLUE")
        .setTimestamp()
        .setFooter(`hurt#6666 <3`)
        message.channel.send(help)
    }else if(!message.mentions.channels.first()) return;
    let poll = message.mentions.channels.first()
    if(!poll){
        let help = new discord.RichEmbed()
        .setTitle(`Help for announcement command!`)
        .setDescription(`Usage: !announce #[channel] [text]\nAdmin permission required!`)
        .setColor("BLUE")
        .setTimestamp()
        .setFooter(`hurt#6666 <3`)
        message.channel.send(help)
    }else{
    let announcement = new discord.RichEmbed()
    .setTitle(`Announcement by ${message.author.username}!`)
    .setDescription(mg)
    .setColor("BLUE")
    .setFooter(`hurt#6666 <3`)
    .setTimestamp()
    poll.send(announcement)
}
}